In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('data\Online Retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [4]:
df.shape

(541909, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [6]:
# remove rows with null Customer IDs
df = df[df['CustomerID' ].notna()]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[ns]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB

In [7]:
#convert Costomer ID data type from float to integer
df.loc[:, 'CustomerID'] = df['CustomerID'].astype('int')
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int32
Country                object
dtype: object

In [8]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [9]:
df[(df.Quantity==0) | (df.UnitPrice <= 0)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,2010-12-16 14:36:00,0.0,16560,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,2010-12-21 13:45:00,0.0,14911,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,2011-01-06 16:41:00,0.0,13081,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,2011-01-06 16:41:00,0.0,13081,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,2011-01-13 15:10:00,0.0,15107,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2011-02-10 13:08:00,0.0,17560,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,2011-03-23 10:25:00,0.0,13239,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,2011-03-30 12:45:00,0.0,13113,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,2011-04-04 14:42:00,0.0,14410,United Kingdom
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,2011-04-14 18:57:00,0.0,12457,Switzerland
187613,553000,47566,PARTY BUNTING,4,2011-05-12 15:21:00,0.0,17667,United Kingdom
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,2011-05-20 14:13:00,0.0,12415,Australia
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,2011-07-26 12:24:00,0.0,16818,United Kingdom
282912,561669,22960,JAM MAKING SET WITH JARS,11,2011-07-28 17:09:00,0.0,12507,Spain
285657,561916,M,Manual,1,2011-08-01 11:44:00,0.0,15581,United Kingdom
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,2011-08-11 11:42:00,0.0,14911,EIRE
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,2011-08-26 14:19:00,0.0,14646,Netherlands
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,2011-08-26 14:19:00,0.0,14646,Netherlands
314747,564651,22955,36 FOIL STAR CAKE CASES,144,2011-08-26 14:19:00,0.0,14646,Netherlands
314748,564651,21786,POLKADOT RAIN HAT,144,2011-08-26 14:19:00,0.0,14646,Netherlands
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 12:22:00,0.0,16133,United Kingdom
361825,568384,M,Manual,1,2011-09-27 09:46:00,0.0,12748,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,2011-10-06 08:17:00,0.0,15804,United Kingdom
395529,571035,M,Manual,1,2011-10-13 12:50:00,0.0,12446,RSA
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,2011-10-26 14:36:00,0.0,18059,United Kingdom
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,2011-11-03 11:26:00,0.0,12415,Australia
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,2011-11-03 11:47:00,0.0,14110,United Kingdom
436961,574252,M,Manual,1,2011-11-03 13:24:00,0.0,12437,France
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,2011-11-04 11:55:00,0.0,12431,Australia
446125,574879,22625,RED KITCHEN SCALES,2,2011-11-07 13:22:00,0.0,13014,United Kingdom
446793,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,2011-11-07 16:34:00,0.0,13985,United Kingdom
446794,574920,23480,MINI LIGHTS WOODLAND MUSHROOMS,1,2011-11-07 16:34:00,0.0,13985,United Kingdom
454463,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,2011-11-10 11:49:00,0.0,13081,United Kingdom
454464,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,2011-11-10 11:49:00,0.0,13081,United Kingdom
479079,577129,22464,HANGING METAL HEART LANTERN,4,2011-11-17 19:52:00,0.0,15602,United Kingdom
479546,577168,M,Manual,1,2011-11-18 10:42:00,0.0,12603,Germany
480649,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,2011-11-18 13:23:00,0.0,12444,Norway
485985,577696,M,Manual,1,2011-11-21 11:57:00,0.0,16406,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom

In [10]:
df.drop(df.index[df.UnitPrice == 0], inplace=True)

In [11]:
df[(df.Quantity==0) | (df.UnitPrice <= 0)].shape

(0, 8)

In [12]:
df['Country'].value_counts()

United Kingdom          361854
Germany                   9493
France                    8490
EIRE                      7483
Spain                     2532
Netherlands               2367
Belgium                   2069
Switzerland               1876
Portugal                  1480
Australia                 1256
Norway                    1085
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
USA                        291
Israel                     250
Unspecified                244
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         57
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     17
Saudi Arabia                10
Name: Country, dtype: int64

In [13]:
df[df.Quantity<=0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom

In [14]:
df[df.InvoiceNo.str.startswith('C') == 1]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom

In [15]:
#check whether the invoice numbers always start with 'C' wherever the negative quantities occur
set(df[df.InvoiceNo.str.startswith('C') == 1].index) - set(df[df.Quantity<=0].index)

set()

In [16]:
set(df[df.Quantity<=0].index) - set(df[df.InvoiceNo.str.startswith('C') == 1].index)

set()

Conclusion: all the rows with negative quantity have the Invoices start with 'C' which may stand for cancelation

In [17]:
negative_quantity_df = df[df.Quantity<=0].copy()
negative_quantity_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom

In [18]:
negative_quantity_df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom

In [19]:
negative_quantity_df.InvoiceNo.str.len().unique()

array([7], dtype=int64)

In [20]:
negative_quantity_df['InvoiceNum'] = negative_quantity_df.InvoiceNo.str.slice(1).astype('int')
negative_quantity_df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int32
Country                object
InvoiceNum              int32
dtype: object

In [21]:
negative_quantity_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNum
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom,536379
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom,536383
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom,536391
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom,536391
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom,536391

In [22]:
positive_quantity_df = df[df.Quantity > 0].copy()
positive_quantity_df.shape, positive_quantity_df.dtypes

((397884, 8),
 InvoiceNo              object
 StockCode              object
 Description            object
 Quantity                int64
 InvoiceDate    datetime64[ns]
 UnitPrice             float64
 CustomerID              int32
 Country                object
 dtype: object)

In [23]:
positive_quantity_df['InvoiceNum'] = positive_quantity_df.InvoiceNo.astype('int')
positive_quantity_df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int32
Country                object
InvoiceNum              int32
dtype: object

In [24]:
df[df['CustomerID']==16321]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
64609,541657,22087,PAPER BUNTING WHITE LACE,6,2011-01-20 12:11:00,2.95,16321,Australia
64610,541657,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-01-20 12:11:00,2.95,16321,Australia
64611,541657,21056,DOCTOR'S BAG SOFT TOY,3,2011-01-20 12:11:00,8.95,16321,Australia
64612,541657,22960,JAM MAKING SET WITH JARS,6,2011-01-20 12:11:00,4.25,16321,Australia
84270,543372,22087,PAPER BUNTING WHITE LACE,18,2011-02-07 15:01:00,2.95,16321,Australia
84271,543372,22325,MOBILE VINTAGE HEARTS,3,2011-02-07 15:01:00,4.95,16321,Australia
84299,C543375,22325,MOBILE VINTAGE HEARTS,-3,2011-02-07 15:09:00,4.95,16321,Australia
84300,C543375,22087,PAPER BUNTING WHITE LACE,-18,2011-02-07 15:09:00,2.95,16321,Australia
84301,543376,22325,MOBILE VINTAGE HEARTS,3,2011-02-07 15:10:00,4.95,16321,Australia
84302,543376,22087,PAPER BUNTING WHITE LACE,18,2011-02-07 15:10:00,2.95,16321,Australia
364984,568687,22090,PAPER BUNTING RETROSPOT,12,2011-09-28 14:26:00,2.95,16321,Australia
364985,568687,21198,WHITE HEART CONFETTI IN TUBE,24,2011-09-28 14:26:00,1.65,16321,Australia
365078,568695,22090,PAPER BUNTING RETROSPOT,12,2011-09-28 14:55:00,2.95,16321,Australia
365079,568695,21198,WHITE HEART CONFETTI IN TUBE,24,2011-09-28 14:55:00,1.65,16321,Australia
365080,C568694,22090,PAPER BUNTING RETROSPOT,-12,2011-09-28 14:55:00,2.95,16321,Australia
365081,C568694,21198,WHITE HEART CONFETTI IN TUBE,-24,2011-09-28 14:55:00,1.65,16321,Australia

Observations for orders from the Customer with ID 16321: The cancelations came before or at the same time when the orders were placed.

In [25]:
df[df['CustomerID']==12668].tail(60)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
134089,547822,22979,PANTRY WASHING UP BRUSH,12,2011-03-25 14:53:00,1.45,12668,Germany
134090,547822,22982,PANTRY PASTRY BRUSH,12,2011-03-25 14:53:00,1.25,12668,Germany
134091,547822,22993,SET OF 4 PANTRY JELLY MOULDS,12,2011-03-25 14:53:00,1.25,12668,Germany
134092,547822,23078,ICE CREAM PEN LIP GLOSS,24,2011-03-25 14:53:00,1.25,12668,Germany
134093,547822,23179,CLOCK MAGNET MUM'S KITCHEN,6,2011-03-25 14:53:00,2.89,12668,Germany
134094,547822,20750,RED RETROSPOT MINI CASES,2,2011-03-25 14:53:00,7.95,12668,Germany
134095,547822,22962,JAM JAR WITH PINK LID,12,2011-03-25 14:53:00,0.85,12668,Germany
134096,547822,22467,GUMBALL COAT RACK,6,2011-03-25 14:53:00,2.55,12668,Germany
134097,547822,22221,CAKE STAND LOVEBIRD 2 TIER PINK,2,2011-03-25 14:53:00,9.95,12668,Germany
134098,547822,22215,CAKE STAND WHITE TWO TIER LACE,2,2011-03-25 14:53:00,8.50,12668,Germany
134099,547822,37500,TEA TIME TEAPOT IN GIFT BOX,12,2011-03-25 14:53:00,4.95,12668,Germany
134100,547822,22123,PING MICROWAVE APRON,12,2011-03-25 14:53:00,1.95,12668,Germany
134101,547822,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,2011-03-25 14:53:00,0.83,12668,Germany
134102,547822,37501,TEA TIME TEA SET IN GIFT BOX,12,2011-03-25 14:53:00,6.95,12668,Germany
134103,547822,POST,POSTAGE,16,2011-03-25 14:53:00,18.00,12668,Germany
145833,C548915,22993,SET OF 4 PANTRY JELLY MOULDS,-12,2011-04-05 09:53:00,1.25,12668,Germany
145834,C548915,22329,ROUND CONTAINER SET OF 5 RETROSPOT,-12,2011-04-05 09:53:00,1.65,12668,Germany
505658,579094,20750,RED RETROSPOT MINI CASES,2,2011-11-28 10:56:00,7.95,12668,Germany
505659,579094,21481,FAWN BLUE HOT WATER BOTTLE,4,2011-11-28 10:56:00,3.75,12668,Germany
505660,579094,21165,BEWARE OF THE CAT METAL SIGN,12,2011-11-28 10:56:00,1.69,12668,Germany
505661,579094,22939,ADULT APRON APPLE DELIGHT,4,2011-11-28 10:56:00,4.95,12668,Germany
505662,579094,47567B,TEA TIME KITCHEN APRON,3,2011-11-28 10:56:00,5.95,12668,Germany
505663,579094,21035,SET/2 RED RETROSPOT TEA TOWELS,6,2011-11-28 10:56:00,3.25,12668,Germany
505664,579094,22895,SET OF 2 TEA TOWELS APPLE AND PEARS,6,2011-11-28 10:56:00,3.25,12668,Germany
505665,579094,21218,RED SPOTTY BISCUIT TIN,6,2011-11-28 10:56:00,3.75,12668,Germany
505666,579094,22199,FRYING PAN RED RETROSPOT,4,2011-11-28 10:56:00,4.25,12668,Germany
505667,579094,21154,RED RETROSPOT OVEN GLOVE,10,2011-11-28 10:56:00,1.25,12668,Germany
505668,579094,47559B,TEA TIME OVEN GLOVE,10,2011-11-28 10:56:00,1.25,12668,Germany
505669,579094,22720,SET OF 3 CAKE TINS PANTRY DESIGN,3,2011-11-28 10:56:00,4.95,12668,Germany
505670,579094,23115,RED APPLES CHOPPING BOARD,3,2011-11-28 10:56:00,4.95,12668,Germany
505671,579094,23114,VINTAGE LEAF CHOPPING BOARD,3,2011-11-28 10:56:00,4.95,12668,Germany
505672,579094,23113,PANTRY CHOPPING BOARD,3,2011-11-28 10:56:00,4.95,12668,Germany
505673,579094,23244,ROUND STORAGE TIN VINTAGE LEAF,6,2011-11-28 10:56:00,1.95,12668,Germany
505674,579094,21531,RED RETROSPOT SUGAR JAM BOWL,6,2011-11-28 10:56:00,2.55,12668,Germany
505675,579094,21535,RED RETROSPOT SMALL MILK JUG,6,2011-11-28 10:56:00,2.55,12668,Germany
505676,579094,21533,RETROSPOT LARGE MILK JUG,3,2011-11-28 10:56:00,4.95,12668,Germany
505677,579094,21232,STRAWBERRY CERAMIC TRINKET POT,24,2011-11-28 10:56:00,1.25,12668,Germany
505678,579094,22064,PINK DOUGHNUT TRINKET POT,12,2011-11-28 10:56:00,1.65,12668,Germany
505679,579094,37450,CERAMIC CAKE BOWL + HANGING CAKES,6,2011-11-28 10:56:00,2.95,12668,Germany
505680,579094,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,6,2011-11-28 10:56:00,2.95,12668,Germany
505681,579094,22303,COFFEE MUG APPLES DESIGN,12,2011-11-28 10:56:00,2.55,12668,Germany
505682,579094,22302,COFFEE MUG PEARS DESIGN,12,2011-11-28 10:56:00,2.55,12668,Germany
505683,579094,22059,CERAMIC STRAWBERRY DESIGN MUG,12,2011-11-28 10:56:00,1.49,12668,Germany
505684,579094,37448,CERAMIC CAKE DESIGN SPOTTED MUG,12,2011-11-28 10:56:00,1.49,12668,Germany
505685,579094,22894,TABLECLOTH RED APPLES DESIGN,2,2011-11-28 10:56:00,9.95,12668,Germany
505686,579094,22649,STRAWBERRY FAIRY CAKE TEAPOT,16,2011-11-28 10:56:00,4.95,12668,Germany
505687,579094,23445,ICE CREAM BUBBLES,20,2011-11-28 10:56:00,0.83,12668,Germany
505688,579094,22419,LIPSTICK PEN RED,12,2011-11-28 10:56:00,0.42,12668,Germany
505689,579094,22644,CERAMIC CHERRY CAKE MONEY BANK,12,2011-11-28 10:56:00,1.45,12668,Germany
505690,579094,48185,DOORMAT FAIRY CAKE,4,2011-11-28 10:56:00,8.25,12668,Germany
505691,579094,22326,ROUND SNACK BOXES SET OF4 WOODLAND,6,2011-11-28 10:56:00,2.95,12668,Germany
505692,579094,22328,ROUND SNACK BOXES SET OF 4 FRUITS,6,2011-11-28 10:56:00,2.95,12668,Germany
505693,579094,22327,ROUND SNACK BOXES SET OF 4 SKULLS,6,2011-11-28 10:56:00,2.95,12668,Germany
505694,579094,22629,SPACEBOY LUNCH BOX,12,2011-11-28 10:56:00,1.95,12668,Germany
505695,579094,POST,POSTAGE,8,2011-11-28 10:56:00,18.00,12668,Germany
521104,C580313,37450,CERAMIC CAKE BOWL + HANGING CAKES,-1,2011-12-02 15:10:00,2.95,12668,Germany
521105,C580313,22649,STRAWBERRY FAIRY CAKE TEAPOT,-3,2011-12-02 15:10:00,4.95,12668,Germany
521106,C580313,22419,LIPSTICK PEN RED,-6,2011-12-02 15:10:00,0.42,12668,Germany
521107,C580313,22303,COFFEE MUG APPLES DESIGN,-2,2011-12-02 15:10:00,2.55,12668,Germany
521108,C580313,21232,STRAWBERRY CERAMIC TRINKET POT,-3,2011-12-02 15:10:00,1.25,12668,Germany

Observations for orders from the Customer with ID 12668: NO orders were placed before cancelation.

In [26]:
set(positive_quantity_df['InvoiceNum']).intersection(set(negative_quantity_df['InvoiceNum']))

set()

Conclusion: No orders were placed before order cancelation. So, we'll remove all the rows with negative quantity.

In [27]:
positive_quantity_df.drop('InvoiceNo', axis=1, inplace=True)
positive_quantity_df.columns

Index(['StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CustomerID', 'Country', 'InvoiceNum'],
      dtype='object')

In [28]:
positive_quantity_df.to_excel('data\online_retail_clean.xlsx')

In [29]:
uk_online_retail_clean = positive_quantity_df[positive_quantity_df.Country=='United Kingdom']
uk_online_retail_clean.shape

(354321, 8)

In [30]:
uk_online_retail_clean.to_excel('data\\uk_online_retail_clean.xlsx')